apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test1
  description: Python app that displays time - named test1
  annotations:
    argocd/app-name: test1
    github.com/project-slug: DaggupatiPavan-1/test1
    backstage.io/kubernetes-namespace: dev
    backstage.io/kubernetes-label-selector: app.kubernetes.io/name=test1
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental
