site_name: 'test1'
site_description: 'Main documentation for the test1'
repo_url: https://github.com/DaggupatiPavan-1/test1
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'
